# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_written',
            field=models.DateField(null=True),
        ),
    ]
