# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170227_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='date',
        ),
    ]
