# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cafe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
