# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_id', to='api.Cafe'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='api.Cafe'),
        ),
    ]
